### ISSUE TITLE
Can it achieve real time when rendering with GGX?

### ISSUE THREAD

**Issue by Zhou-Heng** [shocker-0x15/VLR#1]
Can it achieve real time when rendering with GGX? Thanks.

**Comment by shocker-0x15** [comment]
To be honest, it is difficult for the current generation GPU as of 2018 if you desire a clean image.

[1024x1024, GTX980](https://drive.google.com/open?id=1zZg_p4waZj1DOZgh4mOst1lyisGuuc4p)
The above image was rendered using GTX 980 and the material is UE4 BRDF (it includes GGX).
1\[spp\] took over 150\[ms\].
I have tried a Tesla V100 before, it was approximately three times faster than GTX 980.
This means even with Tesla V100, it will take 50[ms] for 1\[spp\].
However, recently NVIDIA released RTX series GPUs, it might be possible to achieve realtime performance for 1\[spp\] with these GPUs. In this case I need to wait NVIDIA to release the new version of OptiX that supports Turing architecture and RT cores (and need to modify code).

Therefore, it might be possible to achieve realtime for 1\[spp\] in the near future (with moderately sized image).

Unfortunately we can get only very noisy image with 1\[spp\].
Altough we can use OptiX AI denoiser and perhaps it will helps, I guess we need more spp for practically clean image

**Comment by Zhou-Heng** [comment]
Is this because the formula of GGX is too complicated? If we do not take GGX into consideration, i.e., use OptiX to render a scene in which there are only a few ideal specular and ideal diffuse objects, can we achieve real time?

**Comment by shocker-0x15** [comment]
I measured performance of lambert material instead of UE4.
[1024x1024, Lambert, GTX980](https://drive.google.com/open?id=1sU1LmRLR8Ov168kjdnQYdsdaaf_Oy808)
As you can see from the image, duration for 1\[spp\] is almost the same (~= 150\[ms\]) as UE4 material.
This means that material evaluation is not a bottleneck for this case.
Dominant factor is intersection (including Next Event Estimation).

Duration is almost the same but slightly longer with Lambert which itself is simpler to evaluate than UE4.
This is maybe due to changing scattered direction and total amount of ray tracing gets larger (Because it calculates global illumination).

**Comment by shocker-0x15** [comment]
Today's GPUs' performance are generally bound by memory access and VALU is relatively free.
Therefore GGX calculation is not a big problem. (Of cource there are other things should be considered, like divergence, ...)

Thank you for your interest in my renderer.
I will close this issue.
