### ISSUE TITLE
some questions 

### ISSUE THREAD

**Issue by renfudan** [shocker-0x15/VLR#3]
Hi！I have some questions about this project to consult you. It's my honor if you can reply.
1. Do you have the lastest version? If have, can it support OPTIX7?
2. Could GPU driver 432+ run the project without bug?
Thank you very much!

**Comment by shocker-0x15** [comment]
Hello,
I'm now working on porting VLR to OptiX 7 in another branch.
I think I finished almost all part but there are still things to update (and I've been busy for other things recently).

Recent NVIDIA driver has an issue in OpenGL/OptiX 6 interop (while I didn't try very recent drivers, the last driver I know working is 430.64).
If you don't use OpenGL interop feature, I expect the current VLR works.

Thanks

**Comment by bipul-mohanto** [comment]
Hello @shocker-0x15 ! It would be really amazing if the total repository is being ported with the Optix 7.0 or latest. I know it would be really a tiring approach for you as from version 7.0, OptiX has turned out totally a new API. Anyway, is there any update on the porting? Is it working for OptiX 7.0 now?

**Comment by shocker-0x15** [comment]
The main branch is OptiX 7.4.0 based now.
I started OptiX 7 porting activity a long time ago. It was somewhat troublesome and stopped at some point. However I regained motivation a few days ago for some reason and finnaly have completed porting work.

**Comment by bipul-mohanto** [comment]
That is really great.
